//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _67RoleBaseSecurity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> Dummy { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
